### ISSUE TITLE
FetchAssetAsync uses FetchAssetFromApiAsync

### ISSUE THREAD

**Issue by scholtz** [geoffodonnell/dotnet-tinyman-sdk#10]
Hi,

there is issue with FetchAssetAsync. The algod has dropped support for asa fetch from the api, and was transformed only for use by the indexer. 

https://algoexplorer.io/api-dev/v2

if ```tinymanMainnetClient.FetchAssetAsync``` returns 403, it means your algod does not support it any longer.

i am afraid the only solution is to add the indexer to the library

**Comment by geoffodonnell** [comment]
@scholtz

My understanding is that the `/v2/assets/{asset-id}` path remains a part of the Algod REST API v2, it's just no longer accessible at the AlgoExplorer provided endpoints. As such. version 0.2.0.10 changes the default nodes from AlgoExplorer to AlgoNode.

You can continue to use the default constructors, which now connect to AlgoNode maintained nodes (as long as you respect HTTP 429 rate limiting responses from AlgoNode), or, as always, you can maintain your own Algod node and access it as much as you like.
