### ISSUE TITLE
Will there be dotnet core version?

### ISSUE THREAD

**Issue by majestique** [geoffodonnell/dotnet-tinyman-sdk#6]
Unless .NET actually means .NET core? 

> .NET 5 is the next major release of .NET Core following 3.1. We named this new release .NET 5 instead of .NET Core 4 
https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-5

If not, wondering if it's easy to port over to core or if it's fairly simple to run dotnet in Linux. Thanks for all this!

**Comment by geoffodonnell** [comment]
Hi @majestique, this package targets .NET Standard 2.0, which you can see [here](https://github.com/geoffodonnell/dotnet-tinyman-sdk/blob/b61fe01dc533301284e38b019b0a8eb89ac195f2/src/Tinyman/Tinyman.csproj#L4). This is the same target as the Algorand .NET SDK, which will allow you to reference it in either .NET Framework project or a .NET Core project. Longer term, I would expect to target .NET Core only.

If the current target doesn't work for you let me know, it's straightforward enough to target multiple frameworks in a single nuget package.
